- name: Hello World
  connection: web
  tasks:
  - name: Print Hello World
    ansible.builtin.debug:
     msg: "Hello World"












# - name: Hello World
#   hosts: web
#   tasks:
#    - name: Print Hello World 
#      ansible.builtin.debug: