- name: Install and Start nginx
  hosts: node
  become: yes
  tasks: 
  - name: Install nginx
    ansible.builtin.dnf:
     name: nginx
     state: present
  
  - name: Start nginx
    ansible.builtin.service:
     name: nginx
     state: started










# - name: Niginx Installation
#   hosts: web
#   become: yes
#   tasks: 
#   - name: package Installation
#     ansible.builtin.package:
#      name: nginx
#      state: present
  
#   - name: package start
#     ansible.builtin.service:
#      name: nginx
#      state: started