- name: Task level variables
  hosts: local
  connection: local
  vars: 
  - course: "DevOps"
  - trainer: "Rakesh"
  tasks:
  vars: 
  - course: "Ansible"
  - name: Print variables
    ansible.builtin.debug:
     msg: " Course is {{ course }} and trainer is {{ trainer }}"



  