- name: Variables
  hosts: local
  connection: local
  vars_files:
   inventory.ini
  tasks:
   - name: print Variables
     ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}"