- name: Variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: What is your username?
    private: false

  - name: PASSWORD
    prompt: What is your password?
    private: true
  
  tasks:
  - name: Print varibales
    ansible.builtin.debug:
     msg: "username is {{ USERNAME }}, password is {{ PASSWORD }}"