- name: Variable preference
  hosts: local
  connection: local
  vars_files:
   - course.yaml
  vars: 
   course: "DAWS from Play"
   trianer: "Sivakumar"
  vars_prompt:
   name: enter course
   private: false
  tasks:
  - name: Print vars
    vars: 
     course: "Ansible from TASK"
     trianer: "Shiva"
    ansible.builtin.debug:
      msg: "Course is {{ course }}, Trianer is {{ trianer }}"