- name: Filters of Ansible
  hosts: local
  connection: local
  vars:
   topics: Linux, Shell, Ansible, Terraform
  tasks:
  - name: Printing default value
    ansible.builtin.debug:
     msg: "Hello Rakesh {{ GREETINGS | 'good morning'}}"
  
  - name: Splitting a Variable
    ansible.builtin.debug:
     msg: "{{ topics | split(',') }}"