- name: Filters of Ansible
  hosts: local
  connection: local
  vars:
   topics: Linux, Shell, Ansible, Terraform\
   tagsList:
    - course: "DevOps"
    - Duration: "6 months"
  tasks:
  - name: Printing default value
    ansible.builtin.debug:
     msg: "Hello Rakesh {{ GREETINGS | default ('good morning')}}"
  
  - name: Splitting a Variable
    ansible.builtin.debug:
     msg: "{{ topics | split(',') }}"
  
  - name: Converting map to list
    ansible.builtin.debug:
     msg: "{{ tagsList | items2dict }}"

  - name: Converting map to list
    ansible.builtin.debug:
     msg: "{{ tagsMap | dict2items }}"
  