- name: Filters of Ansible
  hosts: local
  connection: local
  vars:
   topics: Linux, Shell, Ansible, Terraform\
   tagsMap:
    course: "DevOps"
    Duration: "6 months"
   course: "DevOps"
   myIP: 255.195.225.220
   tagsList:
    [
        {
            "key": "course",
            "value": "DevOps"
        },
        {
            "key": "Duration",
            "value": "6 months"
        }
    ]
  tasks:
  - name: Printing default value
    ansible.builtin.debug:
     msg: "Hello Rakesh {{ GREETINGS | default ('good morning')}}"
  
  - name: Splitting a Variable
    ansible.builtin.debug:
     msg: "{{ topics | split(',') }}"

  - name: Converting map to list
    ansible.builtin.debug:
     msg: "{{ tagsMap | dict2items }}"
  
  - name: Converting List to map
    ansible.builtin.debug:
     msg: "{{ tagsList | items2dict }}"
  
  - name: Yaml file into a Variable
    ansible.builtin.set_fact:
     students_yaml: "{{ lookup('file', 'students.yaml') | from_json }}"

  - name: Converting yaml to JSON
    ansible.builtin.debug:
     msg: "{{ student_yaml | to_nice_json }}"
  
  - name: To UpperCase
    ansible.builtin.debug:
     msg: "{{ course | upper }}"
  
  - name: To LowerCase
    ansible.builtin.debug:
     msg: "{{ course | upper }}"
  
  - name: check IP
    ansible.builtin.debug:
     msg: "{{ myIP | ansible.utils.ipv4 }}"