- name : Shell vs Command module
  connection: local
  hosts: local
  tasks:
  - name: Command module
    ansible.builtin.command: cat /etc/passwd
  
  - name: Shell module
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: { shell_output }
  
  - name: Print output
    ansible.builtin.debug:
     msg: "{{ shell_outout }}"