- name: Filters Demo
  hosts: local
  connection: local
  vars: 
   names: rakesh, rahul, ramesh, rohan
   topicsMap:
    course: "DAWS"
    duration: 180
    trainer: "shiva"
    language: "english"
   topicsList: 
    [
        {
            "key": "course",
            "value": "DAWS"
        },
        {
            "key": "duration",
            "value": 180
        },
        {
            "key": "trainer",
            "value": "shiva"
        },
        {
            "key": "language",
            "value": "english"
        }
    ]
  tasks:
  - name: greetings
    ansible.builtin.debug:
     msg: "Hello Rakesh, {{ GREETING | default ( 'good morning' ) }}"

  - name: splitting variable
    ansible.builtin.debug:
     msg: "{{ names | split(',') }}"

  - name: converting map to list 
    ansible.builtin.debug:
     msg: "{{ topicsMap | dict2items }}"
  
  - name: converting list to map
    ansible.builtin.debug:
     msg: "{{ topicsList | items2dict }}"
  
  - name: Yaml file into a variable
    ansible.builtin.set_fact:
     students_yaml: "{{ lookup ('file', 'students.yaml') | from_yaml }}"
  
  - name: Converting yaml to JSON
    ansible.builtin.debug:
     msg: "{{ students_yaml | to_nice_json }}"